# Site settings
title: Instant Roofing Prices
tagline: Advanced Roofing Solutions
description: Experience the future of roofing with instant, AI-powered quotes for roof installation, repair, and replacement. Professional roofing services with cutting-edge technology.
url: "https://tim-amredev.github.io"
baseurl: "/future-roof-lead"
lang: en
timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
      permalink: /:basename/

# Include/Exclude
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
  - CNAME
  - LICENSE
  - .git
  - scripts
  - "*.tsx"
  - "*.ts"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

