# Site settings
title: Instant Roofing
description: Advanced roofing solutions powered by cutting-edge technology
baseurl: "/future-roof-lead" # the subpath of your site, e.g. /blog
url: "https://tim-amredev.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# SEO settings
logo: /assets/images/logo.png
social:
  twitter: instantroofing
  facebook: instantroofing
  instagram: instantroofing
  linkedin: instant-roofing

# Contact info
phone: "(555) 123-4567"
email: "tim@americanremodeling.net"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .git
  - .gitignore
  - README.md
  - package.json
  - package-lock.json
  - scripts
  - "*.tsx"
  - "*.ts"

